<a href="https://colab.research.google.com/github/DemirHasicic/AIPortfolio/blob/main/Vjestacka%20Inteligencija%20Vjezbe/VI_lab2_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ZADATAK 1: Rad u Pandas

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [89]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/dataset.csv')
data

id Indeks  Prisustvo Ispit1 Ispit2 Ispit1_popravni Ispit2_popravni  \
0    1  94-ST         10    9.4    7.5           12.08           13.73   
1    2  77-ST         10    8.5      /               /               /   
2    3  69-ST         10     17      /               /               /   
3    4  79-ST          0    7.6    4.8               /               /   
4    5  89-ST         10   10.6   12.5           12.58               /   
5    6  78-ST          0      /      /           13.08           12.83   
6    7  93-ST         10      /   12.5           12.67               /   
7    8  68-ST         10      /      /               /               /   
8    9  83-ST          0      /      /               /               /   
9   10  92-ST         10      /      /               /               /   
10  11  65-ST         10      /      /               /               /   
11  12  70-ST         10     13    7.8               /            16.3   
12  13  90-ST         10   15.6    7.7               /            14.3   
13  14  97-ST         10      /      /               /               /   
14  15  84-ST         10      /      /               /               /   
15  16  98-ST         10   12.5    7.8               /            9.53   
16  17  91-ST         10      /      /               /               /   
17  18  87-ST         10      /      /               /               /   
18  19  76-ST         10      /      /               /               /   
19  20  96-ST         10      /      /               /               /   
20  21  66-ST         10     14    9.7               /              16   
21  22  62-ST         10   12.5      /               /               /   
22  23  74-ST          0   10.7      /           14.58            11.7   
23  24  86-ST         10   13.6   12.5               /               /   
24  25  73-ST         10   12.5    6.5               /           19.07   
25  26  80-ST         10      /      /               /               /   
26  27  63-ST         10   16.6    8.7               /              20   
27  28  72-ST         10      /      /               /               /   
28  29  95-ST          0   10.8   12.5            7.25               /   
29  30  85-ST         10      /   12.5               /               /   
30  31  99-ST         10      /      /           14.17               /   
31  32  41-ST          0      /      /               /               /   
32  33  17-ST          0    7.5    1.7            2.33               /   
33  34  82-ST          0     10    1.5               /               /   
34  35  15-ST          0      /      /               /               /   
35  36  64-ST         10   13.3     15               /               /   
36  37  44-ST         10      /      /               8           14.33   
37  38  71-ST         10      /      /               /               /   
38  39  54-ST         10      /      /               /               /   
39  40  60-ST         10     10      /               /               /   
40  41  48-ST         10      /      /               /               /   
41  42  61-ST         10      /      /               /               /   
42  43   1-ST         10      /      /               /               /   
43  44  88-ST         10      /      /               /               /   
44  45  75-ST         10      /      /            9.83            13.5   
45  46  67-ST         10   16.5      /               /               /   
46  47  81-ST         10   15.7   17.3               /               /   

    UKUPNO Ocjena  
0    35.81      7  
1    35.50      7  
2    39.50      9  
3    12.40      /  
4    35.08      6  
5    25.91      6  
6    35.17      8  
7    50.00      9  
8     0.00      /  
9    42.06      9  
10   43.19      8  
11   39.30      7  
12   39.90      8  
13   41.05      9  
14   43.56      9  
15   38.50      /  
16   43.48      9  
17   35.89      7  
18   27.18      /  
19   41.40      8  
20   40.00      8  
21   42.00 

In [90]:
#a)Učitati datoteku kao Pandas dataframe, te prikazati prvih 5 i posljednjih 10 unosa
data.head()
data.tail(10)
#U zagrade se piše koji broj instanci/redova želimo imati prikazane


id Indeks  Prisustvo Ispit1 Ispit2 Ispit1_popravni Ispit2_popravni  \
37  38  71-ST         10      /      /               /               /   
38  39  54-ST         10      /      /               /               /   
39  40  60-ST         10     10      /               /               /   
40  41  48-ST         10      /      /               /               /   
41  42  61-ST         10      /      /               /               /   
42  43   1-ST         10      /      /               /               /   
43  44  88-ST         10      /      /               /               /   
44  45  75-ST         10      /      /            9.83            13.5   
45  46  67-ST         10   16.5      /               /               /   
46  47  81-ST         10   15.7   17.3               /               /   

    UKUPNO Ocjena  
37   42.16      8  
38   19.35      /  
39   38.50      6  
40   10.00      6  
41   23.12      /  
42   10.00      /  
43   37.00      7  
44   33.33      6  
45   39.50      7  
46   43.00      8

In [91]:
#b)Ispisati samo podatke vezane za redovne parcijalne ispite(Ispit1 i Ispit2¸
data.loc[:,'Ispit1']

0      9.4
1      8.5
2       17
3      7.6
4     10.6
5        /
6        /
7        /
8        /
9        /
10       /
11      13
12    15.6
13       /
14       /
15    12.5
16       /
17       /
18       /
19       /
20      14
21    12.5
22    10.7
23    13.6
24    12.5
25       /
26    16.6
27       /
28    10.8
29       /
30       /
31       /
32     7.5
33      10
34       /
35    13.3
36       /
37       /
38       /
39      10
40       /
41       /
42       /
43       /
44       /
45    16.5
46    15.7
Name: Ispit1, dtype: object

In [92]:
data.loc[:,'Ispit2']

0      7.5
1        /
2        /
3      4.8
4     12.5
5        /
6     12.5
7        /
8        /
9        /
10       /
11     7.8
12     7.7
13       /
14       /
15     7.8
16       /
17       /
18       /
19       /
20     9.7
21       /
22       /
23    12.5
24     6.5
25       /
26     8.7
27       /
28    12.5
29    12.5
30       /
31       /
32     1.7
33     1.5
34       /
35      15
36       /
37       /
38       /
39       /
40       /
41       /
42       /
43       /
44       /
45       /
46    17.3
Name: Ispit2, dtype: object

In [93]:
#c)Ispisati sve studente koji su izgubili prisustvo
data.loc[data['Prisustvo']==0]

id Indeks  Prisustvo Ispit1 Ispit2 Ispit1_popravni Ispit2_popravni  \
3    4  79-ST          0    7.6    4.8               /               /   
5    6  78-ST          0      /      /           13.08           12.83   
8    9  83-ST          0      /      /               /               /   
22  23  74-ST          0   10.7      /           14.58            11.7   
28  29  95-ST          0   10.8   12.5            7.25               /   
31  32  41-ST          0      /      /               /               /   
32  33  17-ST          0    7.5    1.7            2.33               /   
33  34  82-ST          0     10    1.5               /               /   
34  35  15-ST          0      /      /               /               /   

    UKUPNO Ocjena  
3    12.40      /  
5    25.91      6  
8     0.00      /  
22   27.08      /  
28   23.50      /  
31    5.87      /  
32    9.20      /  
33   16.00      /  
34    0.00      /

In [94]:
#d)Ispisati indeks, ukupne bodove i ocjenu za sve studente sa ocjenom 8 ili viš

data.loc[(data['Ocjena'] =='8')| (data['Ocjena']=='9')| (data['Ocjena']=='10'), ['Indeks', 'UKUPNO','Ocjena']]

Indeks  UKUPNO Ocjena
2   69-ST   39.50      9
6   93-ST   35.17      8
7   68-ST   50.00      9
9   92-ST   42.06      9
10  65-ST   43.19      8
12  90-ST   39.90      8
13  97-ST   41.05      9
14  84-ST   43.56      9
16  91-ST   43.48      9
19  96-ST   41.40      8
20  66-ST   40.00      8
21  62-ST   42.00      8
25  80-ST   39.45      8
26  63-ST   46.60      8
35  64-ST   38.30      8
37  71-ST   42.16      8
46  81-ST   43.00      8

In [95]:
#e)Sve nedostajuce vrijednosti zamijeniti sa vrijednoscu np.nan
data.replace('/', np.nan, inplace=True)

In [96]:
#f)Izbaciti sve studente koji nemaju ocjenu
bez_ocjena = data[data['Ocjena']=='/'].index
data.drop(bez_ocjena, inplace=True)
data = data.reset_index(drop=True)
 #Pošto se u pozadini .csv reazlizira kao hash mapa nakon izbacivanja nece biti nuzno ocuvan redoslijed

In [97]:
#g)Kreirati kolonu ispit1_finalu koju ćete za svakog studenta upisati onaj rezultat ispita koji je bolji (na
#primjer, ako je student bolje uradio popravni ispit, onda tu pišete bodove sa popravnog, a u protivnom sa
#redovnog);

data['Ispit1_final'] = np.where(data['Ispit1']>data['Ispit1_popravni'],data['Ispit1'], data['Ispit1_popravni'])
#data['Ispit1_final'] = data['Ispit1']
#data.loc[data['Ispit1'] < data['Ispit1_popravni'],'Ispit1_final'] = data['Ispit1_popravni']
data
#Radi za sve osim za prvi


id Indeks  Prisustvo Ispit1 Ispit2 Ispit1_popravni Ispit2_popravni  \
0    1  94-ST         10    9.4    7.5           12.08           13.73   
1    2  77-ST         10    8.5    NaN             NaN             NaN   
2    3  69-ST         10     17    NaN             NaN             NaN   
3    4  79-ST          0    7.6    4.8             NaN             NaN   
4    5  89-ST         10   10.6   12.5           12.58             NaN   
5    6  78-ST          0    NaN    NaN           13.08           12.83   
6    7  93-ST         10    NaN   12.5           12.67             NaN   
7    8  68-ST         10    NaN    NaN             NaN             NaN   
8    9  83-ST          0    NaN    NaN             NaN             NaN   
9   10  92-ST         10    NaN    NaN             NaN             NaN   
10  11  65-ST         10    NaN    NaN             NaN             NaN   
11  12  70-ST         10     13    7.8             NaN            16.3   
12  13  90-ST         10   15.6    7.7             NaN            14.3   
13  14  97-ST         10    NaN    NaN             NaN             NaN   
14  15  84-ST         10    NaN    NaN             NaN             NaN   
15  16  98-ST         10   12.5    7.8             NaN            9.53   
16  17  91-ST         10    NaN    NaN             NaN             NaN   
17  18  87-ST         10    NaN    NaN             NaN             NaN   
18  19  76-ST         10    NaN    NaN             NaN             NaN   
19  20  96-ST         10    NaN    NaN             NaN             NaN   
20  21  66-ST         10     14    9.7             NaN              16   
21  22  62-ST         10   12.5    NaN             NaN             NaN   
22  23  74-ST          0   10.7    NaN           14.58            11.7   
23  24  86-ST         10   13.6   12.5             NaN             NaN   
24  25  73-ST         10   12.5    6.5             NaN           19.07   
25  26  80-ST         10    NaN    NaN             NaN             NaN   
26  27  63-ST         10   16.6    8.7             NaN              20   
27  28  72-ST         10    NaN    NaN             NaN             NaN   
28  29  95-ST          0   10.8   12.5            7.25             NaN   
29  30  85-ST         10    NaN   12.5             NaN             NaN   
30  31  99-ST         10    NaN    NaN           14.17             NaN   
31  32  41-ST          0    NaN    NaN             NaN             NaN   
32  33  17-ST          0    7.5    1.7            2.33             NaN   
33  34  82-ST          0     10    1.5             NaN             NaN   
34  35  15-ST          0    NaN    NaN             NaN             NaN   
35  36  64-ST         10   13.3     15             NaN             NaN   
36  37  44-ST         10    NaN    NaN               8           14.33   
37  38  71-ST         10    NaN    NaN             NaN             NaN   
38  39  54-ST         10    NaN    NaN             NaN             NaN   
39  40  60-ST         10     10    NaN             NaN             NaN   
40  41  48-ST         10    NaN    NaN             NaN             NaN   
41  42  61-ST         10    NaN    NaN             NaN             NaN   
42  43   1-ST         10    NaN    NaN             NaN             NaN   
43  44  88-ST         10    NaN    NaN             NaN             NaN   
44  45  75-ST         10    NaN    NaN            9.83            13.5   
45  46  67-ST         10   16.5    NaN             NaN             NaN   
46  47  81-ST         10   15.7   17.3             NaN             NaN   

    UKUPNO Ocjena Ispit1_final  
0    35.81      7          9.4  
1    35.50      7          NaN  
2    39.50      9          NaN  
3    12.40    NaN          NaN  
4    35.08      6        12.58  
5    25.91      6        13.08  
6    35.17      8        12.67  
7    50.00      9          NaN  
8     0.00    NaN          NaN  
9    42.06      9          NaN  
10   43.19      8          NaN  
11   39.30      7          NaN  
12   39.90      8     

In [98]:
data['Ispit2_final'] = np.where(data['Ispit2']>data['Ispit2_popravni'], data['Ispit2'], data['Ispit2_popravni'])
data

id Indeks  Prisustvo Ispit1 Ispit2 Ispit1_popravni Ispit2_popravni  \
0    1  94-ST         10    9.4    7.5           12.08           13.73   
1    2  77-ST         10    8.5    NaN             NaN             NaN   
2    3  69-ST         10     17    NaN             NaN             NaN   
3    4  79-ST          0    7.6    4.8             NaN             NaN   
4    5  89-ST         10   10.6   12.5           12.58             NaN   
5    6  78-ST          0    NaN    NaN           13.08           12.83   
6    7  93-ST         10    NaN   12.5           12.67             NaN   
7    8  68-ST         10    NaN    NaN             NaN             NaN   
8    9  83-ST          0    NaN    NaN             NaN             NaN   
9   10  92-ST         10    NaN    NaN             NaN             NaN   
10  11  65-ST         10    NaN    NaN             NaN             NaN   
11  12  70-ST         10     13    7.8             NaN            16.3   
12  13  90-ST         10   15.6    7.7             NaN            14.3   
13  14  97-ST         10    NaN    NaN             NaN             NaN   
14  15  84-ST         10    NaN    NaN             NaN             NaN   
15  16  98-ST         10   12.5    7.8             NaN            9.53   
16  17  91-ST         10    NaN    NaN             NaN             NaN   
17  18  87-ST         10    NaN    NaN             NaN             NaN   
18  19  76-ST         10    NaN    NaN             NaN             NaN   
19  20  96-ST         10    NaN    NaN             NaN             NaN   
20  21  66-ST         10     14    9.7             NaN              16   
21  22  62-ST         10   12.5    NaN             NaN             NaN   
22  23  74-ST          0   10.7    NaN           14.58            11.7   
23  24  86-ST         10   13.6   12.5             NaN             NaN   
24  25  73-ST         10   12.5    6.5             NaN           19.07   
25  26  80-ST         10    NaN    NaN             NaN             NaN   
26  27  63-ST         10   16.6    8.7             NaN              20   
27  28  72-ST         10    NaN    NaN             NaN             NaN   
28  29  95-ST          0   10.8   12.5            7.25             NaN   
29  30  85-ST         10    NaN   12.5             NaN             NaN   
30  31  99-ST         10    NaN    NaN           14.17             NaN   
31  32  41-ST          0    NaN    NaN             NaN             NaN   
32  33  17-ST          0    7.5    1.7            2.33             NaN   
33  34  82-ST          0     10    1.5             NaN             NaN   
34  35  15-ST          0    NaN    NaN             NaN             NaN   
35  36  64-ST         10   13.3     15             NaN             NaN   
36  37  44-ST         10    NaN    NaN               8           14.33   
37  38  71-ST         10    NaN    NaN             NaN             NaN   
38  39  54-ST         10    NaN    NaN             NaN             NaN   
39  40  60-ST         10     10    NaN             NaN             NaN   
40  41  48-ST         10    NaN    NaN             NaN             NaN   
41  42  61-ST         10    NaN    NaN             NaN             NaN   
42  43   1-ST         10    NaN    NaN             NaN             NaN   
43  44  88-ST         10    NaN    NaN             NaN             NaN   
44  45  75-ST         10    NaN    NaN            9.83            13.5   
45  46  67-ST         10   16.5    NaN             NaN             NaN   
46  47  81-ST         10   15.7   17.3             NaN             NaN   

    UKUPNO Ocjena Ispit1_final Ispit2_final  
0    35.81      7          9.4          7.5  
1    35.50      7          NaN          NaN  
2    39.50      9          NaN          NaN  
3    12.40    NaN          NaN          NaN  
4    35.08      6        12.58          NaN  
5    25.91      6        13.08        12.83  
6    35.17      8        12.67          NaN  
7    50.00      9          NaN          NaN  
8     0.00    NaN          NaN       

In [99]:
data.drop(['Ispit1','Ispit1_popravni', 'Ispit2', 'Ispit2_popravni'],axis=1, inplace=True)

In [100]:
data.to_csv('izvjestaj_modificirano.csv', sep=';')


In [101]:
import pickle

In [102]:
pickle.dump('izvjestaj_modificirano.csv', open("izvjestaj_modificirano_pickle.p", "wb"), protocol = pickle.HIGHEST_PROTOCOL)



# 'ZADATAK' 3: Klasični algoritam mašinskog učenja

In [103]:
#a) Ucitali smo podatke za iris iz postojece biblioteke load_iris, te ispisale atribute i nazive labela za taj dataset
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target
feature_names = iris.feature_names
target_names  = iris.target_names
print("Nazivi znacajki : ", feature_names)
print("Nazivi labela : ", target_names)
print("\nPrvih 5 redova X :\n", x[:5])

Nazivi znacajki :  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Nazivi labela :  ['setosa' 'versicolor' 'virginica']

Prvih 5 redova X :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [104]:
#b) Podjela skupa podataka na testni i trening skup
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)
print(y_train.shape)
print(y_test.shape)
print(x_test.shape)
print(x_train.shape)

(105,)
(45,)
(45, 4)
(105, 4)


In [105]:
#c) Primjenjujemo odgovarajući algoritam na testni i trening skup u ovom slucaju k - NN , ovaj algoritam svaki podataka mapira kao n-dimenzionalnu tačku. Klasa podatka se zatim
# odredđuje na osnovu k-najblizih tacaka u tom prostoru. Uzima se ona klasa koja se pojavljuje najcesce u blizini k najblizih susjeda
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
classifier_kn = KNeighborsClassifier(n_neighbors = 31)
classifier_kn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=31)

In [106]:
#d) Sada algoritam primjenjujemo na testnom skupu, kako bi se odredila uspjesnost, pisemo x_test jer su x podaci iris.data , OPTIMALNA VRIJEDNOST K <=31
y_pred = classifier_kn.predict(x_test)
print("Tacnost :  ", metrics.accuracy_score(y_test, y_pred))

Tacnost :   0.9777777777777777


# ZADATAK 4 : Deep Learning

In [107]:
#a) Keras ima ucitane podatke slika sa brojevima njih 70000 i vec su podijeljeni na trening i test podatke, samo ih ucitamo iz kerasa
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [108]:
#b) Kako bi se ove slike mogle poslati u neuralnu mrezu potrebno ih je pretvoriti u brojeve u pokretnom zarezu, te ih svesti na opseg izmedju 0 i 1
#posto pikseli greyscale slika zauzimaju vrijednosti izmedju 0 i 255 mozemo ih jednostavno podijeliti sa 255 i dobiti trazeni opseg
train_images = x_train.reshape ((x_train.shape[0], 28*28))
train_images = train_images.astype('float32') /255

test_images = x_test.reshape((x_test.shape[0], 28*28))
test_images = test_images.astype('float32')/255
print(test_images.shape)
print(train_images.shape)
print(test_images)


(10000, 784)
(60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [109]:
#c) Nakon što su podaci sprmeni moze se napraviti jednostavan model neuralne mreze. Kreira se model pa se dodaju slojevi
#Model se moze zamisliti kao sito za podatke gdje svaki sloj filtrira podatke (nadamo se na koristan nacin), posljednji sloj je softmax sloj i on ispisuje
#niz vjerovatnoca (cija je suma 1), svaka vrijednost u tom nizu oznacava s kojom vjerovatncom slika pripada odredjenoj cifri gdje cifra predstavlja objekat

In [110]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape = (28*28,)))
network.add(layers.Dense(10, activation = 'softmax'))

In [111]:
#d) Nakon definisanja modela, potrebno ga je i trenirati , kako bi to bilo moguce model se treba i kompajlirati
#kompajliranje se sastoji od odabira 3 parametra 1)funkcije gubitka(Oznaca kako neuralna mreza moze mjeriti svoje performanse, te na osnovu nje prilagodjava procese treniranja)
#2) Optimizator mehanizam kojim se neuralna mreza aktualizira, 3)metrike koje se prate tokom testiranja i treniranja , samo tačnost gledamo / kod funkcije gubitka sve performanse
network.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [112]:
#e) Izlaz iz neuralne mreze je niz od 10 elemenata . Shodno tome izvrsavamo pravilno prilagođavanje labele izlazu, izvrsimo one-hot kodiranje istih. Ovo kodiranje predstavlja pretvaranje
#labele u niz od 10 elemenata  npr 3 -> [0 0 0 1 0 0 0 0 0 0] (kao indeksacija 0,1,2,3,4,5,6,7,8,9, pa je na mjestu gdje je 3 stavljena jedinica)
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)


In [113]:
#f) Spremno sve da se mreza trenira
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 3s 5ms/step - loss: 0.2651 - accuracy: 0.9247
Epoch 2/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1076 - accuracy: 0.9684
Epoch 3/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0721 - accuracy: 0.9785
Epoch 4/5
469/469 [==============================] - 3s 5ms/step - loss: 0.0529 - accuracy: 0.9837
Epoch 5/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0383 - accuracy: 0.9882


In [114]:
#g)
test_loss, test_acc = network.evaluate(test_images, test_labels)
train_loss, train_acc = network.evaluate(train_images, train_labels)
print("Tacnost za testni skup: ", test_acc)
print("Tacnost za trening skup: ", train_acc)

1875/1875 [==============================] - 6s 3ms/step - loss: 0.0313 - accuracy: 0.9906
Tacnost za testni skup:  0.9779999852180481
Tacnost za trening skup:  0.9905833601951599
